ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "consent_at" TIMESTAMPTZ;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "consent_version" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "attribution" JSONB;
